apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appviewer-rolebinding
  namespace: tap-dev01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-viewer
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: GROUP=NO-UUID-DAYO
