---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: api-auto-registration
imagePullSecrets:
  - name: cert-manager-registry-creds
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-registry-creds
  namespace: api-auto-registration
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: api-portal
imagePullSecrets:
  - name: cert-manager-registry-creds
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-registry-creds
  namespace: api-portal
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: metadata-store
imagePullSecrets:
  - name: cert-manager-registry-creds
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-registry-creds
  namespace: metadata-store
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: tap-gui
imagePullSecrets:
  - name: cert-manager-registry-creds
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-registry-creds
  namespace: tap-gui
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: user@yourdomain.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: contour
            podTemplate:
              spec:
                serviceAccountName: tap-acme-http01-solver